const EError = {
  ROUTING_ERROR: 1,
  INVALID_TYPE_ERROR: 2,
  DATABASE_ERROR: 3,
  INVALID_VALUE_ERROR: 4,
  AUTH_ERROR: 5,
  AUTHORIZATION_ERROR: 6,
  INVALID_REQUEST_ERROR: 7,
  INTERNAL_SERVER_ERROR: 8,
  RESOURCE_NOT_FOUND_ERROR: 9,
  VALIDATION_ERROR: 10,
  DATABASE_CONNECTION_ERROR: 11,
  DATABASE_ACCESS_ERROR: 12,
  RATE_LIMIT_EXCEEDED_ERROR: 13,
  TIMEOUT_ERROR: 14,
  MISSING_DEPENDENCY_ERROR: 15,
  DATA_FORMAT_ERROR: 16,
  OPERATION_NOT_ALLOWED_ERROR: 17,
  SERVICE_UNAVAILABLE_ERROR: 18,
  UNSUPPORTED_REQUEST_ERROR: 19
}

module.exports = {
  EError
}
